name: Upload to S3 and Deploy to Greengrass

on: workflow_dispatch
  # uncomment below to enable the workflow
  # push:
  #   branches:
  #     - release/lomby/2024.10/2024.12
    paths:
      - 'autoware.repos'

jobs:
  upload-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Upload new 'autoware.repos' file to 'latest' and 'archive'
        run: |
          TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
          aws s3 cp autoware.repos s3://lomby-greengrass/autoware-repos-updates/latest/autoware.repos
          aws s3 cp autoware.repos s3://lomby-greengrass/autoware-repos-updates/archive/$TIMESTAMP-autoware.repos

      - name: Create Greengrass Deployment
        run: |
          aws greengrassv2 create-deployment \
            --target-arn arn:aws:iot:ap-northeast-1:${{ secrets.AWS_ACCOUNT_ID }}:thinggroup/lomby-lma2-things \
            --deployment-name "AutowareReposUpdate-$(date +%Y-%m-%d-%H-%M-%S)" \
            --components '{"AutowareReposUpdater": {"componentVersion": "1.0.0"}}' \
            --region ap-northeast-1

      - name: Check Deployment Status
        run: |
          DEPLOYMENT_ID=$(aws greengrassv2 list-deployments --target-arn arn:aws:iot:ap-northeast-1:${{ secrets.AWS_ACCOUNT_ID }}:thinggroup/lomby-lma2-things --query 'deployments[0].deploymentId' --output text)
          aws greengrassv2 get-deployment --deployment-id $DEPLOYMENT_ID
