name: mirror-main-branch

on:
  workflow_dispatch

jobs:
  mirror-main-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: zofrex/mirror-branch@v1
        with:
          target-branch: humble
